import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { loadStripe } from '@stripe/stripe-js';
import { Brain, Check, Clock, ArrowLeft, Zap, Star, Shield, Download } from 'lucide-react';

// Replace with your actual Stripe publishable key
const stripePromise = loadStripe('pk_test_PLACEHOLDER');

const Paywall: React.FC = () => {
  const [countdown, setCountdown] = useState(15 * 60); // 15 minutes in seconds
  const [isProcessing, setIsProcessing] = useState(false);

  useEffect(() => {
    const timer = setInterval(() => {
      setCountdown(prev => prev > 0 ? prev - 1 : 0);
    }, 1000);
    return () => clearInterval(timer);
  }, []);

  const formatTime = (seconds: number) => {
    const mins = Math.floor(seconds / 60);
    const secs = seconds % 60;
    return `${mins}:${secs.toString().padStart(2, '0')}`;
  };

  const handlePurchase = async () => {
    setIsProcessing(true);
    
    try {
      const stripe = await stripePromise;
      
      if (!stripe) {
        throw new Error('Stripe failed to load');
      }

      // In a real app, you'd call your backend to create a checkout session
      // For demo purposes, we'll simulate a successful payment
      
      // Simulate API call delay
      await new Promise(resolve => setTimeout(resolve, 2000));
      
      // Redirect to success page or show success state
      // For now, we'll just show an alert
      alert('Payment successful! (Demo mode - no actual payment processed)');
      
      // In production, redirect to results with AI analysis
      window.location.href = '/results?premium=true';
      
    } catch (error) {
      console.error('Payment error:', error);
      alert('Payment failed. Please try again.');
    } finally {
      setIsProcessing(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-deep-purple via-electric-blue to-neon-purple text-warm-white">
      {/* Header */}
      <div className="sticky top-0 bg-deep-purple/90 backdrop-blur-sm border-b border-white/10 z-40">
        <div className="max-w-4xl mx-auto px-6 py-4">
          <button 
            onClick={() => window.history.back()}
            className="flex items-center gap-2 text-bright-cyan hover:text-neon-purple transition-colors"
          >
            <ArrowLeft className="w-5 h-5" />
            <span>Back to Results</span>
          </button>
        </div>
      </div>

      <div className="max-w-4xl mx-auto px-6 py-12">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: -30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="text-center mb-12"
        >
          <div className="inline-flex items-center gap-3 card px-6 py-3 mb-6">
            <Brain className="w-6 h-6 text-neon-purple" />
            <span className="text-bright-cyan font-semibold">Premium Analysis</span>
          </div>
          
          <h1 className="text-4xl md:text-5xl font-serif font-bold mb-4 text-gradient">
            Unlock Your Complete
            <br />
            Personality Profile
          </h1>
          <p className="text-xl text-warm-white/80 max-w-2xl mx-auto">
            Get AI-powered insights, personalized recommendations, and detailed analysis 
            tailored to your unique HEXACO profile
          </p>
        </motion.div>

        {/* Countdown Timer */}
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="card p-6 mb-8 text-center bg-gradient-to-r from-red-500/20 to-orange-500/20 border-red-400/30"
        >
          <div className="flex items-center justify-center gap-2 mb-2">
            <Clock className="w-5 h-5 text-orange-400" />
            <span className="text-orange-400 font-semibold">Limited Time Offer</span>
          </div>
          <p className="text-warm-white/90">
            Your results expire in: <span className="text-orange-400 font-bold text-lg">{formatTime(countdown)}</span>
          </p>
        </motion.div>

        <div className="grid lg:grid-cols-3 gap-8 mb-12">
          {/* What's Included */}
          <motion.div
            initial={{ opacity: 0, x: -50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.8, delay: 0.3 }}
            className="lg:col-span-2"
          >
            <h2 className="text-2xl font-bold text-neon-purple mb-6">What's Included</h2>
            <div className="space-y-4">
              {[
                {
                  icon: Brain,
                  title: "AI-Powered Deep Analysis",
                  description: "Personalized insights generated by advanced AI based on your unique HEXACO scores"
                },
                {
                  icon: Zap,
                  title: "Actionable Development Plan",
                  description: "Specific strategies for personal growth, career advancement, and relationship improvement"
                },
                {
                  icon: Star,
                  title: "Detailed Trait Breakdown",
                  description: "In-depth analysis of all 24 personality facets with practical implications"
                },
                {
                  icon: Download,
                  title: "Professional PDF Report",
                  description: "Beautifully formatted report you can save, share, or use for professional development"
                }
              ].map((feature, index) => (
                <motion.div
                  key={feature.title}
                  initial={{ opacity: 0, y: 20 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ duration: 0.5, delay: 0.1 * index }}
                  className="card p-6 flex items-start gap-4"
                >
                  <div className="bg-gradient-to-r from-neon-purple to-bright-cyan p-2 rounded-lg">
                    <feature.icon className="w-5 h-5 text-white" />
                  </div>
                  <div>
                    <h3 className="font-semibold text-warm-white mb-2">{feature.title}</h3>
                    <p className="text-warm-white/80 text-sm">{feature.description}</p>
                  </div>
                </motion.div>
              ))}
            </div>
          </motion.div>

          {/* Pricing Card */}
          <motion.div
            initial={{ opacity: 0, x: 50 }}
            animate={{ opacity: 1, x: 0 }}
            transition={{ duration: 0.8, delay: 0.5 }}
            className="lg:col-span-1"
          >
            <div className="card p-8 bg-gradient-to-br from-neon-purple/20 to-bright-cyan/20 border-neon-purple/50 relative">
              {/* Popular badge */}
              <div className="absolute -top-3 left-1/2 transform -translate-x-1/2">
                <span className="bg-gradient-to-r from-neon-purple to-bright-cyan px-4 py-1 rounded-full text-white text-sm font-semibold">
                  Most Popular
                </span>
              </div>

              <div className="text-center mb-6">
                <h3 className="text-2xl font-bold text-neon-purple mb-2">Complete Analysis</h3>
                <div className="mb-4">
                  <span className="text-4xl font-bold text-bright-cyan">$4.99</span>
                  <span className="text-warm-white/60 ml-2">one-time</span>
                </div>
                <p className="text-warm-white/80 text-sm">Instant access to your full personality profile</p>
              </div>

              <div className="space-y-3 mb-6">
                {[
                  "AI-powered personality analysis",
                  "Detailed 24-facet breakdown",
                  "Personal development plan",
                  "Professional PDF report",
                  "Relationship insights",
                  "Career recommendations"
                ].map((feature) => (
                  <div key={feature} className="flex items-center gap-3">
                    <Check className="w-4 h-4 text-bright-cyan" />
                    <span className="text-warm-white/90 text-sm">{feature}</span>
                  </div>
                ))}
              </div>

              <button
                onClick={handlePurchase}
                disabled={isProcessing}
                className="w-full btn-primary py-4 text-lg font-semibold disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {isProcessing ? (
                  <span className="flex items-center justify-center gap-2">
                    <div className="w-5 h-5 border-2 border-white border-t-transparent rounded-full animate-spin"></div>
                    Processing...
                  </span>
                ) : (
                  'Get Complete Analysis'
                )}
              </button>

              <div className="flex items-center justify-center gap-4 mt-4 text-xs text-warm-white/60">
                <div className="flex items-center gap-1">
                  <Shield className="w-3 h-3" />
                  <span>Secure Payment</span>
                </div>
                <div className="flex items-center gap-1">
                  <Download className="w-3 h-3" />
                  <span>Instant Access</span>
                </div>
              </div>
            </div>
          </motion.div>
        </div>

        {/* Security & Guarantees */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8, delay: 0.7 }}
          className="text-center"
        >
          <p className="text-warm-white/60 text-sm mb-4">
            🔒 Payments secured by Stripe • 📱 Access on all devices • ⚡ Instant delivery
          </p>
          <p className="text-warm-white/40 text-xs">
            By purchasing, you agree to our Terms of Service and Privacy Policy.
            <br />
            Questions? Contact support@hexacotest.com
          </p>
        </motion.div>
      </div>
    </div>
  );
};

export default Paywall;
