export const hexacoQuestions = {
  questionnaire_name: 'HEXACO-60 Personality Inventory',
  instructions:
    'Please answer all 60 questions. There are no right or wrong answers. Describe yourself as you generally are now, not as you wish to be. Read each statement carefully and select the option that best describes you. Response scale: 1 = strongly disagree, 2 = disagree, 3 = neutral (neither agree nor disagree), 4 = agree, 5 = strongly agree.',
  scales: [
    {
      domain: 'Honesty-Humility',
      facets: [
        { name: 'Sincerity', items: [6, 30, 54] },
        { name: 'Fairness', items: [12, 36, 60] },
        { name: 'Greed-Avoidance', items: [18, 42] },
        { name: 'Modesty', items: [24, 48] },
      ],
    },
    {
      domain: 'Emotionality',
      facets: [
        { name: 'Fearfulness', items: [5, 29, 53] },
        { name: 'Anxiety', items: [11, 35] },
        { name: 'Dependence', items: [17, 41] },
        { name: 'Sentimentality', items: [23, 47, 59] },
      ],
    },
    {
      domain: 'Extraversion',
      facets: [
        { name: 'Social Self-Esteem', items: [4, 28, 52] },
        { name: 'Social Boldness', items: [10, 34, 58] },
        { name: 'Sociability', items: [16, 40] },
        { name: 'Liveliness', items: [22, 46] },
      ],
    },
    {
      domain: 'Agreeableness (versus Anger)',
      facets: [
        { name: 'Forgiveness', items: [3, 27] },
        { name: 'Gentleness', items: [9, 33, 51] },
        { name: 'Flexibility', items: [15, 39, 57] },
        { name: 'Patience', items: [21, 45] },
      ],
    },
    {
      domain: 'Conscientiousness',
      facets: [
        { name: 'Organization', items: [2, 26] },
        { name: 'Diligence', items: [8, 32] },
        { name: 'Perfectionism', items: [14, 38, 50] },
        { name: 'Prudence', items: [20, 44, 56] },
      ],
    },
    {
      domain: 'Openness to Experience',
      facets: [
        { name: 'Aesthetic Appreciation', items: [1, 25] },
        { name: 'Inquisitiveness', items: [7, 31] },
        { name: 'Creativity', items: [13, 37, 49] },
        { name: 'Unconventionality', items: [19, 43, 55] },
      ],
    },
  ],
  items: [
    {
      id: 1,
      text: 'I rarely express my opinions in group meetings.',
      reverse_scored: true,
      domain: 'Openness to Experience',
      facet: 'Aesthetic Appreciation',
    },
    {
      id: 2,
      text: 'I plan ahead and organize things, to avoid scrambling at the last minute.',
      reverse_scored: false,
      domain: 'Conscientiousness',
      facet: 'Organization',
    },
    {
      id: 3,
      text: 'I rarely hold a grudge, even against people who have badly wronged me.',
      reverse_scored: false,
      domain: 'Agreeableness (versus Anger)',
      facet: 'Forgiveness',
    },
    {
      id: 4,
      text: 'I feel that I am a person of worth, at least on an equal plane with others.',
      reverse_scored: false,
      domain: 'Extraversion',
      facet: 'Social Self-Esteem',
    },
    { id: 5, text: 'I worry a lot about mistakes I have made.', reverse_scored: false, domain: 'Emotionality', facet: 'Fearfulness' },
    {
      id: 6,
      text: 'I would never use flattery to get a raise or promotion, even if I thought it would succeed.',
      reverse_scored: false,
      domain: 'Honesty-Humility',
      facet: 'Sincerity',
    },
    {
      id: 7,
      text: 'I am interested in many different kinds of ideas.',
      reverse_scored: false,
      domain: 'Openness to Experience',
      facet: 'Inquisitiveness',
    },
    { id: 8, text: 'I work hard to achieve my goals.', reverse_scored: false, domain: 'Conscientiousness', facet: 'Diligence' },
    {
      id: 9,
      text: 'I tend to be lenient in judging other people.',
      reverse_scored: true,
      domain: 'Agreeableness (versus Anger)',
      facet: 'Gentleness',
    },
    {
      id: 10,
      text: 'In social situations, I am usually the one who makes the first move.',
      reverse_scored: true,
      domain: 'Extraversion',
      facet: 'Social Boldness',
    },
    { id: 11, text: "I sometimes can't help worrying about things.", reverse_scored: false, domain: 'Emotionality', facet: 'Anxiety' },
    {
      id: 12,
      text: 'I would be tempted to use illegal means to get money if I could be sure of not being caught.',
      reverse_scored: true,
      domain: 'Honesty-Humility',
      facet: 'Fairness',
    },
    {
      id: 13,
      text: 'I enjoy thinking about things that are new and different.',
      reverse_scored: false,
      domain: 'Openness to Experience',
      facet: 'Creativity',
    },
    {
      id: 14,
      text: 'I often do things on the spur of the moment.',
      reverse_scored: true,
      domain: 'Conscientiousness',
      facet: 'Perfectionism',
    },
    {
      id: 15,
      text: 'I am usually quite flexible in my opinions when people disagree with me.',
      reverse_scored: true,
      domain: 'Agreeableness (versus Anger)',
      facet: 'Flexibility',
    },
    { id: 16, text: 'I enjoy social gatherings.', reverse_scored: false, domain: 'Extraversion', facet: 'Sociability' },
    {
      id: 17,
      text: 'I feel like crying when I see others suffering.',
      reverse_scored: false,
      domain: 'Emotionality',
      facet: 'Dependence',
    },
    {
      id: 18,
      text: 'I want to be rich and powerful, even if it means taking advantage of others.',
      reverse_scored: false,
      domain: 'Honesty-Humility',
      facet: 'Greed-Avoidance',
    },
    {
      id: 19,
      text: 'I think that paying attention to radical ideas is a waste of time.',
      reverse_scored: true,
      domain: 'Openness to Experience',
      facet: 'Unconventionality',
    },
    { id: 20, text: 'I make an effort to keep my promises.', reverse_scored: true, domain: 'Conscientiousness', facet: 'Prudence' },
    {
      id: 21,
      text: 'Most people tend to get angry more quickly than I do.',
      reverse_scored: true,
      domain: 'Agreeableness (versus Anger)',
      facet: 'Patience',
    },
    { id: 22, text: 'I am a cheerful person.', reverse_scored: false, domain: 'Extraversion', facet: 'Liveliness' },
    {
      id: 23,
      text: 'I am not easily bothered by things that would distress most people.',
      reverse_scored: false,
      domain: 'Emotionality',
      facet: 'Sentimentality',
    },
    {
      id: 24,
      text: 'I think that I am a very important person.',
      reverse_scored: true,
      domain: 'Honesty-Humility',
      facet: 'Modesty',
    },
    {
      id: 25,
      text: 'I enjoy looking at works of art.',
      reverse_scored: false,
      domain: 'Openness to Experience',
      facet: 'Aesthetic Appreciation',
    },
    { id: 26, text: 'I often leave my belongings in a mess.', reverse_scored: true, domain: 'Conscientiousness', facet: 'Organization' },
    {
      id: 27,
      text: 'I find it easy to forgive people who have hurt me.',
      reverse_scored: false,
      domain: 'Agreeableness (versus Anger)',
      facet: 'Forgiveness',
    },
    {
      id: 28,
      text: 'I am often uncomfortable in social situations.',
      reverse_scored: true,
      domain: 'Extraversion',
      facet: 'Social Self-Esteem',
    },
    { id: 29, text: 'I am afraid of many things.', reverse_scored: false, domain: 'Emotionality', facet: 'Fearfulness' },
    {
      id: 30,
      text: 'I would never try to get my way by using flattery or false promises.',
      reverse_scored: true,
      domain: 'Honesty-Humility',
      facet: 'Sincerity',
    },
    {
      id: 31,
      text: 'I am not interested in learning about new cultures.',
      reverse_scored: true,
      domain: 'Openness to Experience',
      facet: 'Inquisitiveness',
    },
    {
      id: 32,
      text: 'I am easily distracted from my tasks.',
      reverse_scored: true,
      domain: 'Conscientiousness',
      facet: 'Diligence',
    },
    {
      id: 33,
      text: "I tend to be critical of other people's shortcomings.",
      reverse_scored: false,
      domain: 'Agreeableness (versus Anger)',
      facet: 'Gentleness',
    },
    {
      id: 34,
      text: 'I can usually talk my way out of anything.',
      reverse_scored: false,
      domain: 'Extraversion',
      facet: 'Social Boldness',
    },
    { id: 35, text: 'I rarely feel anxious or worried.', reverse_scored: true, domain: 'Emotionality', facet: 'Anxiety' },
    {
      id: 36,
      text: 'I would never cheat on my taxes, even if I had a chance to do so.',
      reverse_scored: false,
      domain: 'Honesty-Humility',
      facet: 'Fairness',
    },
    { id: 37, text: 'I enjoy creative activities.', reverse_scored: false, domain: 'Openness to Experience', facet: 'Creativity' },
    { id: 38, text: 'I am a perfectionist.', reverse_scored: false, domain: 'Conscientiousness', facet: 'Perfectionism' },
    {
      id: 39,
      text: 'I am stubborn and set in my ways.',
      reverse_scored: false,
      domain: 'Agreeableness (versus Anger)',
      facet: 'Flexibility',
    },
    { id: 40, text: 'I prefer to do things alone.', reverse_scored: true, domain: 'Extraversion', facet: 'Sociability' },
    {
      id: 41,
      text: 'I rarely need emotional support from others.',
      reverse_scored: true,
      domain: 'Emotionality',
      facet: 'Dependence',
    },
    {
      id: 42,
      text: 'I am not especially interested in money or luxury.',
      reverse_scored: true,
      domain: 'Honesty-Humility',
      facet: 'Greed-Avoidance',
    },
    {
      id: 43,
      text: 'I am open to new ways of doing things.',
      reverse_scored: false,
      domain: 'Openness to Experience',
      facet: 'Unconventionality',
    },
    { id: 44, text: 'I make decisions carefully.', reverse_scored: true, domain: 'Conscientiousness', facet: 'Prudence' },
    {
      id: 45,
      text: 'I rarely get angry, even when I have good reason to do so.',
      reverse_scored: false,
      domain: 'Agreeableness (versus Anger)',
      facet: 'Patience',
    },
    { id: 46, text: 'I am a lively person.', reverse_scored: true, domain: 'Extraversion', facet: 'Liveliness' },
    { id: 47, text: 'I am a very sentimental person.', reverse_scored: false, domain: 'Emotionality', facet: 'Sentimentality' },
    {
      id: 48,
      text: 'I believe that I am entitled to more respect than the average person.',
      reverse_scored: true,
      domain: 'Honesty-Humility',
      facet: 'Modesty',
    },
    { id: 49, text: 'I have a vivid imagination.', reverse_scored: true, domain: 'Openness to Experience', facet: 'Creativity' },
    { id: 50, text: 'I often check my work for errors.', reverse_scored: false, domain: 'Conscientiousness', facet: 'Perfectionism' },
    {
      id: 51,
      text: 'I am a very forgiving person.',
      reverse_scored: false,
      domain: 'Agreeableness (versus Anger)',
      facet: 'Gentleness',
    },
    {
      id: 52,
      text: 'I feel comfortable in the presence of strangers.',
      reverse_scored: true,
      domain: 'Extraversion',
      facet: 'Social Self-Esteem',
    },
    { id: 53, text: 'I am not afraid of anything.', reverse_scored: true, domain: 'Emotionality', facet: 'Fearfulness' },
    {
      id: 54,
      text: 'I would never pretend to like someone in order to get that person to do favors for me.',
      reverse_scored: false,
      domain: 'Honesty-Humility',
      facet: 'Sincerity',
    },
    {
      id: 55,
      text: 'I am interested in abstract ideas.',
      reverse_scored: true,
      domain: 'Openness to Experience',
      facet: 'Unconventionality',
    },
    { id: 56, text: 'I often act without thinking.', reverse_scored: true, domain: 'Conscientiousness', facet: 'Prudence' },
    {
      id: 57,
      text: 'I am willing to make compromises.',
      reverse_scored: true,
      domain: 'Agreeableness (versus Anger)',
      facet: 'Flexibility',
    },
    { id: 58, text: 'I am good at influencing people.', reverse_scored: false, domain: 'Extraversion', facet: 'Social Boldness' },
    {
      id: 59,
      text: 'I am not easily moved by emotional appeals.',
      reverse_scored: true,
      domain: 'Emotionality',
      facet: 'Sentimentality',
    },
    {
      id: 60,
      text: 'I would be tempted to steal something if I knew I could never be caught.',
      reverse_scored: true,
      domain: 'Honesty-Humility',
      facet: 'Fairness',
    },
  ],
  scoring_notes:
    "Items marked with 'reverse_scored': true must have their responses reversed prior to computing scale scores (e.g., 5 becomes 1, 4 becomes 2, 3 remains 3, 2 becomes 4, 1 becomes 5). Facet scale scores are computed as the mean of the (recoded) items within that facet. Domain (factor) scale scores are computed as the mean of the facet scale scores within that domain.",
};
